### PR TITLE
Fix api problem: 405 Method Not allowed and 404 Not Found

### LINKED ISSUE #1: Error: not working
contributors are free to fix the openai issue

### PR DESCRIPTION
**Pull request by KunalSin9h**
As i dont have OPENAI_API_KEY (i have used my 2 accounts for free quote) i will not able to test it locally. 

Fixes #1

### CODE REVIEW

File: app/api/chat/route.ts [hunk 1]
```diff
@@ -27,8 +27,7 @@ export async function POST(req: Request) {
             : null
         }
           Implement standard grammar and punctuation, and ensure that small details and spelling errors are corrected. Please base the changes on this context: ${article}
-          ${article.slice(-1) === "." ? "" : "."
-        }`,
+          ${article.slice(-1) === "." ? "" : "."}`,
```
Comment (KunalSin9h) [inline app/api/chat/route.ts:30]: this is just format fix, automatically done by vscode

**Comment by nermalcat69** [comment]
Thanks @KunalSin9h 💯 💯
